### ISSUE TITLE
Env variables in static.json

### ISSUE THREAD

**Issue by kmiyashiro** [heroku/heroku-buildpack-ember-cli#10]
This is probably a question for the static buildpack, but how would you insert values from environment variables into static.json? For example, I have a different API proxy URL for my canary environment than my production environment.

Also, the readme still says "updates your application's asset prefix each time the CDN_HOST variable is changed on Heroku", is that still true?

**Comment by jmonster** [comment]
Apologies for the delay, apparently I haven't been `watching` this repo!

https://github.com/heroku/heroku-buildpack-static#interpolating-env-var-values

> It's common to want to be able to test the frontend against various backends. The origin key supports environment variable substitution using ${ENV_VAR_NAME}. For instance, if there was a staging and production Heroku app for your API, you could setup the config above like the following:

``` json
{
  "proxies": {
    "/api/": {
      "origin": "https://${API_APP_NAME}.herokuapp.com/"
    }
  }
}
```

As for CDN, we encountered some quirks and mostly removed mention of it.. I see I missed the part you're quoting. The answer is technically yes: https://github.com/heroku/heroku-buildpack-ember-cli/blob/master/scripts/set-cdn-prefix ... this will look for `THISISAPLACEHOLDERFORTHECDNHOSTVALUE` and replace it with the `CDN_HOST` variable. 

You would need to have the CDN value set to `THISISAPLACEHOLDERFORTHECDNHOSTVALUE` at build time for this mechanism to actually work. It's admittedly hacky and ugly, so that's why we removed most references to it. You'd set this value in your ember-cli-build file:

``` js
fingerprint: {
  prepend: 'THISISAPLACEHOLDERFORTHECDNHOSTVALUE'
}
```
